name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Publish package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-package: jdk
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Create Maven settings.xml
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: '[{"id": "github", "configuration": {"httpHeaders": {"property": {"name": "Authorization", "value": "Bearer ${{ secrets.GHP_TOKEN }}"}}}}]'
      - name: Publish package to GitHub Packages
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
